MySQL:
  enabled: false
  host: 'localhost'
  database: 'db'
  username: 'user'
  password: 'pass'
  port: 3306

Settings:
  tax-per-transaction: 10
  cash-top-update: 600
  commands:
    cash:
      cmd: cash
      aliases: []
    shop:
      cmd: shop
      aliases: []

Item:
  type: PLAYER_HEAD
  owner: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjgwOWQyZTY5NjEwZjFlNmI3NWZlMGQ0NTk4ZTQ0MWU1NjAzMjVkMmQ1MmQ5N2NmNjY4NTljNDRmYTNkOGE3OSJ9fX0=
  name: '&6Cash &7[&fx{amount}&7]'
  lore:
    - '&7Ative esse item para ganhar'
    - '&7cash e gastar no &f/shop&7!'

Messages:
  never-seen: '&6&lVoltz&f&lMC &8&l➜ &cEsse jogador nunca entrou no servidor!'
  offline-player: '&6&lVoltz&f&lMC &8&l➜ &cEsse jogador está offline!'
  invalid-amount: '&6&lVoltz&f&lMC &8&l➜ &cValor inválido!'
  pay-min: '&6&lVoltz&f&lMC &8&l➜ &cA quantia precisa ser acima de {tax}!'
  insufficient-cash: '&6&lVoltz&f&lMC &8&l➜ &cVocê não possui cash suficiente!'
  send-to-yourself: '&6&lVoltz&f&lMC &8&l➜ &cVocê não pode enviar cash para si mesmo!'
  choose-amount:
    - ''
    - '&6&lVoltz&f&lMC &8&l➜ &7Digite no chat quantos itens você deseja comprar!'
    - ''
    - ' &8▶ &7Item: &f{item}'
    - ' &8▶ &7Preço: &6{price}'
    - ''
  successful-purchased:
    - ''
    - '&6&lVoltz&f&lMC &8&l➜ &7Compra efetuada com sucesso!'
    - ''
    - ' &8▶ &7Item adquirido: &f{item}'
    - ' &8▶ &7Quantia: &fx{amount}'
    - ' &8▶ &7Preço: &6{price}'
    - ''
  cash-sent:
    - ''
    - '&6&lVoltz&f&lMC &8&l➜ &7Transação efetuada com sucesso! Confira abaixo as informações:'
    - ''
    - ' &8▶ &7Moeda: &6Cash'
    - ' &8▶ &7Enviado para: &f{target}'
    - ' &8▶ &7Saldo enviado: &f{amount}'
    - ' &8▶ &7Saldo recebido: &f{received} &7(&f-10%&7)'
    - ' &8▶ &7ID: &f#{id}'
    - ''
  cash-received:
    - ''
    - '&6&lVoltz&f&lMC &8&l➜ &7Uma nova transação foi efetuada! Confira abaixo as informações:'
    - ''
    - ' &8▶ &7Moeda: &6Cash'
    - ' &8▶ &7Feita por: &f{actor}'
    - ' &8▶ &7Saldo recebido: &f{received}'
    - ' &8▶ &7ID: &f#{id}'
    - ''
  confirm:
    - ''
    - '&6&lVoltz&f&lMC &8&l➜ &7Digite o comando novamente para confirmar a transação!'
    - ''
    - ' &8▶ &7Moeda: &6Cash'
    - ' &8▶ &7Enviando para: &f{target}'
    - ' &8▶ &7Saldo a ser enviado: &f{amount}'
    - ' &8▶ &7Saldo a ser recebido: &f{received} &7(&f-10%&7)'
    - ''

NumberFormatter:
  - "k"
  - "M"
  - "B"
  - "T"
  - "Q"
  - "QQ"
  - "S"
  - "SS"
  - "O"
  - "N"
  - "D"